baseURL = "https://bookshelf-it.benelog.net/"
languageCode = "ko-KR	"
defaultContentLanguage = "ko"
title = "IT 책장"
theme = "papercss-hugo-theme"
disqusShortname = "bookshelf-it-benelog"
googleAnalytics = "UA-138559685-3"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  homeMetaContent = "IT 책장"
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

[menu]
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 3
  [[menu.nav]]
    name = "Source"
    url = "https://github.com/benelog/bookshelf-it"
    weight = 4
